language: node_js
sudo: required
services:
  - docker
after_success:
  - bin/docker_push.sh
  # - bin/kubernetes_deploy.sh
script:
  return 0
addons:
  apt:
    packages:
      - docker-ce
notifications:
  email: false
