language: node_js
node_js:
  "10"
sudo: required
services:
  - docker
after_success:
  - bin/docker_push.sh
  - bin/kubernetes_deploy.sh
install: false
script: return 0
addons:
  apt:
    packages:
      - docker-ce
notifications:
  email: false
